/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mac;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asus
 */
public class financialmanager extends javax.swing.JFrame {
String url="jdbc:mysql://localhost:3306/mac";
String username="root";
String password="8287";
    /**
     * Creates new form financialmanager
     */
    public financialmanager() {
        initComponents();
        selectfmb();
        selectfma();
        selectfmc();
    }
public void selectfmb()
{ try{
          Connection con =(DriverManager.getConnection(url,username,password));  
         java.sql.Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("select EmployeID,EmployeName,EmployeSalary  from hrmanager");
          fmtable2.setModel(DbUtils.resultSetToTableModel(rs));
            
    }                                 
catch (Exception e){
    e.printStackTrace();}}
public void selectfma()
{ try{
          Connection con =(DriverManager.getConnection(url,username,password));  
         java.sql.Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("select s.itemCode,s.Earning,s.Due,p.itemCost from sellsmanager s inner join productionmanager p on s.itemCode=p.itemCode ");
          fmtable1.setModel(DbUtils.resultSetToTableModel(rs));
            
    }                                 
catch (Exception e){
    e.printStackTrace();}}
public void selectfmc()
{ try{
          Connection con =(DriverManager.getConnection(url,username,password));  
         java.sql.Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("select * from financialmanager ");
          fmtable3.setModel(DbUtils.resultSetToTableModel(rs));
            
    }                                 
catch (Exception e){
    e.printStackTrace();}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        fadd = new javax.swing.JButton();
        fdel = new javax.swing.JButton();
        fclr = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fmtable1 = new javax.swing.JTable();
        ectext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        apetext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mcptext = new javax.swing.JTextField();
        sdtext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ecsum = new javax.swing.JButton();
        apesum = new javax.swing.JButton();
        mcpsum = new javax.swing.JButton();
        sdsum = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        fmtable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        fmtable3 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Employe cost");

        fadd.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fadd.setForeground(new java.awt.Color(153, 0, 0));
        fadd.setText("Add");
        fadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faddMouseClicked(evt);
            }
        });
        fadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faddActionPerformed(evt);
            }
        });

        fdel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fdel.setForeground(new java.awt.Color(153, 0, 0));
        fdel.setText("Delete");
        fdel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fdelMouseClicked(evt);
            }
        });
        fdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdelActionPerformed(evt);
            }
        });

        fclr.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fclr.setForeground(new java.awt.Color(153, 0, 0));
        fclr.setText("Clear");
        fclr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fclrMouseClicked(evt);
            }
        });

        fmtable1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fmtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Code", "Earned", "Cost", "Due"
            }
        ));
        fmtable1.setRowHeight(30);
        jScrollPane2.setViewportView(fmtable1);
        if (fmtable1.getColumnModel().getColumnCount() > 0) {
            fmtable1.getColumnModel().getColumn(2).setHeaderValue("Cost");
            fmtable1.getColumnModel().getColumn(3).setHeaderValue("Due");
        }

        ectext.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ectext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ectextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Financial Manager");

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1658, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("All Product Earned");

        apetext.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        apetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apetextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Cost of all products");

        mcptext.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        mcptext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcptextActionPerformed(evt);
            }
        });

        sdtext.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        sdtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdtextActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("Sum of Due");

        ecsum.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ecsum.setForeground(new java.awt.Color(153, 0, 0));
        ecsum.setText("Get Sum");
        ecsum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ecsumMouseClicked(evt);
            }
        });
        ecsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecsumActionPerformed(evt);
            }
        });

        apesum.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        apesum.setForeground(new java.awt.Color(153, 0, 0));
        apesum.setText("Get Sum");
        apesum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apesumMouseClicked(evt);
            }
        });
        apesum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apesumActionPerformed(evt);
            }
        });

        mcpsum.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        mcpsum.setForeground(new java.awt.Color(153, 0, 0));
        mcpsum.setText("Get Sum");
        mcpsum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mcpsumMouseClicked(evt);
            }
        });
        mcpsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcpsumActionPerformed(evt);
            }
        });

        sdsum.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        sdsum.setForeground(new java.awt.Color(153, 0, 0));
        sdsum.setText("Get Sum");
        sdsum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sdsumMouseClicked(evt);
            }
        });
        sdsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdsumActionPerformed(evt);
            }
        });

        fmtable2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fmtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "EmployeID", "Employe Name", "Salary"
            }
        ));
        fmtable2.setRowHeight(30);
        jScrollPane3.setViewportView(fmtable2);

        fmtable3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fmtable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EmployeSalary", "IetmCost", "Money earned", "Due"
            }
        ));
        fmtable3.setRowHeight(30);
        jScrollPane4.setViewportView(fmtable3);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("Report for CEO");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Month");

        month.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        year.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("Year");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setText("←");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(28, 28, 28))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(sdtext, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(mcpsum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(sdsum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ecsum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fadd, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(108, 108, 108)
                                        .addComponent(fdel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(fclr, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(201, 201, 201))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(ectext, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(apetext, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(mcptext, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27)
                                        .addComponent(apesum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(411, 411, 411))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ectext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ecsum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apetext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apesum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mcpsum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mcptext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdsum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fdel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fadd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fclr, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(196, 196, 196))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(847, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void faddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faddActionPerformed

    private void fdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fdelActionPerformed

    private void ectextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ectextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ectextActionPerformed

    private void ecsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecsumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecsumActionPerformed

    private void apesumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apesumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apesumActionPerformed

    private void mcpsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcpsumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcpsumActionPerformed

    private void sdsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdsumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdsumActionPerformed

    private void ecsumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ecsumMouseClicked
try{
          Connection con =(DriverManager.getConnection(url,username,password));  
         String sql="select sum(EmployeSalary) from hrmanager";
         java.sql.PreparedStatement pst=con.prepareStatement(sql);
            java.sql.ResultSet rs=pst.executeQuery();
            if(rs.next()){
             String sumes=rs.getString("sum(EmployeSalary)");
            ectext.setText(sumes);
            }
    }                                 
catch (Exception e){
    e.printStackTrace();}
// TODO add your handling code here:
    }//GEN-LAST:event_ecsumMouseClicked

    private void apesumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apesumMouseClicked
        // TODO add your handling code here:
        try{
          Connection con =(DriverManager.getConnection(url,username,password));  
         String sql="select sum(Earning) from sellsmanager";
         java.sql.PreparedStatement pst=con.prepareStatement(sql);
            java.sql.ResultSet rs=pst.executeQuery();
            if(rs.next()){
             String sumes=rs.getString("sum(Earning)");
            apetext.setText(sumes);
            }
    }                                 
catch (Exception e){
    e.printStackTrace();}
    }//GEN-LAST:event_apesumMouseClicked

    private void mcpsumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcpsumMouseClicked
        // TODO add your handling code here:
        try{
          Connection con =(DriverManager.getConnection(url,username,password));  
         String sql="select sum(itemCost) from productionmanager";
         java.sql.PreparedStatement pst=con.prepareStatement(sql);
            java.sql.ResultSet rs=pst.executeQuery();
            if(rs.next()){
             String sumes=rs.getString("sum(itemCost)");
            mcptext.setText(sumes);
            }
    }                                 
catch (Exception e){
    e.printStackTrace();}
    }//GEN-LAST:event_mcpsumMouseClicked

    private void sdsumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdsumMouseClicked
        // TODO add your handling code here:
         try{
          Connection con =(DriverManager.getConnection(url,username,password));  
         String sql="select sum(Due) from sellsmanager";
         java.sql.PreparedStatement pst=con.prepareStatement(sql);
            java.sql.ResultSet rs=pst.executeQuery();
            if(rs.next()){
             String sumes=rs.getString("sum(Due)");
            sdtext.setText(sumes);
            }
    }                                 
catch (Exception e){
    e.printStackTrace();}
    }//GEN-LAST:event_sdsumMouseClicked

    private void faddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faddMouseClicked
        // TODO add your handling code here:
        try{
           Connection con =(DriverManager.getConnection(url,username,password));  
           java.sql.PreparedStatement eadd=con.prepareStatement("insert into financialmanager (EmployeSalary,ItemCost,MoneyEarned,MoneyDue,Month,Year) values(?,?,?,?,?,?)");
           eadd.setString (1,ectext.getText());
           eadd.setString (2,apetext.getText());
            eadd.setString (3,mcptext.getText());
           eadd.setString (4,sdtext.getText());
           eadd.setString (5,month.getText());
           eadd.setString (6,year.getText());
           
       int rows=eadd.executeUpdate();
        
            JOptionPane.showMessageDialog(this,"Financial info added successfully");
            con.close();
           selectfmc();
    }                                 
catch (Exception e){
    e.printStackTrace();
}
    }//GEN-LAST:event_faddMouseClicked

    private void fdelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdelMouseClicked
        // TODO add your handling code here:
        if(year.getText().isEmpty()||month.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter the Year and month to be deleted");
        }
        else{
            
        try{
           Connection con =(DriverManager.getConnection(url,username,password));  
String etemp=month.getText();
String etemp2=year.getText();
String Query="delete FROM financialmanager where month='"+etemp+"'"+"&&Year="+etemp2;
       java.sql.Statement st=con.createStatement(); 
       st.executeUpdate(Query);
        
            JOptionPane.showMessageDialog(this,"Financial report deleted successfully");
            con.close();
           selectfmc();
    }                                 
catch (Exception e){
    e.printStackTrace();
}
    }//GEN-LAST:event_fdelMouseClicked
    }
    private void fclrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fclrMouseClicked
        ectext.setText("");
        apetext.setText("");
        mcptext.setText("");
        sdtext.setText("");
        month.setText("");
        year.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_fclrMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void mcptextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcptextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcptextActionPerformed

    private void apetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apetextActionPerformed

    private void sdtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtextActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(financialmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(financialmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(financialmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(financialmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new financialmanager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apesum;
    private javax.swing.JTextField apetext;
    private javax.swing.JButton ecsum;
    private javax.swing.JTextField ectext;
    private javax.swing.JButton fadd;
    private javax.swing.JButton fclr;
    private javax.swing.JButton fdel;
    private javax.swing.JTable fmtable1;
    private javax.swing.JTable fmtable2;
    private javax.swing.JTable fmtable3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton mcpsum;
    private javax.swing.JTextField mcptext;
    private javax.swing.JTextField month;
    private javax.swing.JButton sdsum;
    private javax.swing.JTextField sdtext;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
